SELECT GODINA as "Godina",
	CASE
	WHEN DANNED = 1 THEN 'Ponedeljak'
	WHEN DANNED = 2 THEN 'Utorak'
	WHEN DANNED = 3 THEN 'Sreda'
	WHEN DANNED = 4 THEN 'Četvrtak'
	WHEN DANNED = 5 THEN 'Petak'
	WHEN DANNED = 6 THEN 'Subota'
	ELSE 'Nedelja'
	END as "Dan u nedelji",
	BT AS "Broj transakcija",
	NAZIV as "Mesto transakcije",
	SUM(BT) over (partition by DANNED, GODINA order by danned, godina) as "Broj transakcija po danu"
FROM (SELECT SUM(BROJTRANSAKCIJA) AS BT, V.GODINA, V.DANNED, B.NAZIV
FROM MMW_TRANSAKCIJA T, MMW_BANKOMAT B, MMW_VREME V
WHERE T.VREME_IDVREME = V.IDVREME AND B.IDBANKOMAT = T.BANKOMAT_IDBANKOMAT
	AND V.GODINA IN (2021,2022,2023)
GROUP BY V.GODINA, B.NAZIV, V.DANNED
UNION
SELECT SUM(BROJTRANSAKCIJA) as BT, V.GODINA, V.DANNED, E.NAZIV
FROM MMW_TRANSAKCIJA T, MMW_EKSPOZITURA E, MMW_VREME V
WHERE T.VREME_IDVREME = V.IDVREME AND E.IDEKSPOZITURA = T.EKSPOZITURA_IDEKSPOZITURA
	AND V.GODINA IN (2021,2022,2023)
GROUP BY V.GODINA, E.NAZIV, V.DANNED)
ORDER BY GODINA, NAZIV, DANNED
