SELECT CASE
    	WHEN grupa = 2 THEN '17-26'
    	WHEN grupa = 3 THEN '27-36'
    	WHEN grupa = 4 THEN '37-46'
    	WHEN grupa = 5 THEN '47-56'
    	WHEN grupa = 6 THEN '57-66'
    	WHEN grupa = 7 THEN '67-76'
    	WHEN grupa = 8 THEN '77-86'
    	WHEN grupa = 9 THEN '87-96'
    	ELSE '>96'
   	END as "Starosna grupa",
   	POTROSNJA as "Potrosnja",
   	IDSVRHATRANS as "Sifra",
   	NAZIV as "Opis"
FROM (SELECT FLOOR((R.STAROST + 3) / 10) AS grupa, ABS(SUM(IZNOS)) AS POTROSNJA, S.IDSVRHATRANS, NAZIV
FROM MMW_TRANSAKCIJA T, MMW_RACUN R, MMW_SVRHATRANSAKCIJE S, MMW_VREME V
WHERE T.RACUN_IDRACUN = R.IDRACUN
	AND T.SVRHATRANSAKCIJE_IDSVRHATRANS = S.IDSVRHATRANS
	AND T.VREME_IDVREME = V.IDVREME AND V.GODINA = 2023 AND V.MESECBR <= 6
	AND R.VALUTA = 'RSD' AND T.PRIHOD = 0
GROUP BY FLOOR((R.STAROST + 3) / 10), S.IDSVRHATRANS, NAZIV)
ORDER BY grupa, IDSVRHATRANS
